/** Ronas-inspired monochrome UI tokens — crisp white surfaces and obsidian actions. */
export const LightAppTheme = {
  bg: '#F8FAFC',
  bgElevated: '#FFFFFF',
  card: '#FFFFFF',
  cardHover: '#F1F5F9',
  inputBg: '#F8FAFC',
  border: '#E2E8F0',
  chipBorder: '#E2E8F0',
  accent: '#111827',
  accentSoft: '#F1F5F9',
  onAccent: '#FFFFFF',
  brand: '#0F172A',
  brandSoft: '#F1F5F9',
  warm: '#0F172A',
  warmSoft: '#F1F5F9',
  green: '#0F172A',
  greenSoft: '#F1F5F9',
  text: '#0F172A',
  textMuted: '#64748B',
  textDim: '#94A3B8',
  danger: '#0F172A',
  dangerSoft: '#F1F5F9',
  success: '#0F172A',
  successSoft: '#F1F5F9',
  warning: '#0F172A',
  warningSoft: '#F1F5F9',
  premium: '#0F172A',
  premiumSoft: '#F1F5F9',
  overlay: 'rgba(15, 23, 42, 0.42)',
  shadowColor: '#0F172A',
  white: '#FFFFFF',
  radiusSm: 10,
  radiusMd: 14,
  radiusLg: 16,
  radiusPill: 20,
  radiusBtn: 14,
  buttonHeight: 48,
};

export const DarkAppTheme: typeof LightAppTheme = {
  bg: '#0B0F17',
  bgElevated: '#151B26',
  card: '#151B26',
  cardHover: '#1E293B',
  inputBg: '#1E293B',
  border: '#1F2937',
  chipBorder: '#334155',
  accent: '#FFFFFF',
  accentSoft: '#1E293B',
  onAccent: '#0F172A',
  brand: '#FFFFFF',
  brandSoft: '#1E293B',
  warm: '#FFFFFF',
  warmSoft: '#1E293B',
  green: '#FFFFFF',
  greenSoft: '#1E293B',
  text: '#FFFFFF',
  textMuted: '#94A3B8',
  textDim: '#64748B',
  danger: '#FFFFFF',
  dangerSoft: '#1E293B',
  success: '#FFFFFF',
  successSoft: '#1E293B',
  warning: '#FFFFFF',
  warningSoft: '#1E293B',
  premium: '#FFFFFF',
  premiumSoft: '#1E293B',
  overlay: 'rgba(0, 0, 0, 0.72)',
  shadowColor: '#000000',
  white: '#FFFFFF',
  radiusSm: 10,
  radiusMd: 14,
  radiusLg: 16,
  radiusPill: 20,
  radiusBtn: 14,
  buttonHeight: 48,
};

export type AppThemeTokens = typeof LightAppTheme;

export const AppTheme = LightAppTheme;

export const APP_THEMES = {
  dark: DarkAppTheme,
  light: LightAppTheme,
} as const;

export const SERVICE_COLORS = {
  maintenance: LightAppTheme.text,
  wash: LightAppTheme.text,
  parts: LightAppTheme.text,
  accessories: LightAppTheme.text,
  winch: LightAppTheme.text,
} as const;
