-- PitStop database setup (Supabase SQL editor)
--
-- Fresh project:
--   1. supabase/schema.sql
--   2. supabase/seed.sql
--
-- Existing project with spare_parts table:
--   Run supabase/migrate-to-store.sql once, then re-run seed store rows if needed.
